### ISSUE TITLE
CRUD Pedido

### ISSUE THREAD

**Issue by RafilxTenfen** [douglasfelipebs/TrabalhoFinalGCFUDESC#6]
# Implementar CRUD de Pedido seguindo solicitação do cliente.

**Contato de Intermédio com o Cliente:** Gabriel Willemann.
**Equipe de Desenvolvimento:** Douglas Felipe Bussmann Siedschlag & Rafael Tenfen.

### O cadastro de Pedidos deve possuir os seguintes campos:

- Código 
- Data e Hora  
- Valor Total 
- Os Produtos Relacionado
- O Cliente Relacionado

### Tarefas: 

- [x] Criar tabela pedido no banco de dados
- [x] Criar tabela de relacionamento entre pedido e produtos no banco de dados
- [x] Adaptar template Front-End para as necessidades da ferramenta
- [x] Criar rotina de Pedido

**Comment by douglasfelipebs** [comment]
Não foi possível implementar a Alteração de pedidos em tempo hábil. Implementar futuramente
